#!/usr/bin/env bash

set -o errexit                              # Force exit at the first error
set -o nounset                              # Treat unset variables as an error
set -o pipefail

# Formatting options:
declare -r bold=$(tput bold)
declare -r normal=$(tput sgr0)

[[ -z "${1:-}" ]] && { echo -e "Usage:\n\t$0 <search term>"; exit 1; }
declare -r search_term="$1"

# List of tables excluded from search, separated by \|:
declare -r exclude_tables="auditlog"

for t in $(tabdump | grep -v $exclude_tables); do
    declare r="$(tabdump $t | grep $search_term)"
    if [[ -n "${r:-}" ]]; then
        echo -ne "${bold}$t${normal}:\n\t"
        echo -e "${r//$'\n'/--==--}" | sed -e 's/--==--/\n\t/g'
    fi
done